dist: trusty
language: python
services:
  - docker
python:
  - "2.7"
  - "3.6"
env:
  - TRAVIS=True TEST_MODE=INTEGRATION_TESTS
  - TRAVIS=True TEST_MODE=FLAKE8
  - TRAVIS=True TEST_MODE=TF2
install:
  # code below is taken from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - docker build -f tests/Dockerfile -t test_image --build-arg PY_VERSION=$TRAVIS_PYTHON_VERSION .

# command to run tests
script:
  - if [[ "$TEST_MODE" == "INTEGRATION_TESTS" ]]; then
      docker run test_image py.test tests/integration_tests;
    elif [[ "$TEST_MODE" == "FLAKE8" ]]; then
      docker run test_image flake8;
    else
      docker run test_image py.test tests/kerastuner --cov-config .coveragerc --cov=kerastuner;
    fi
